groups:
  - name: alert_rule
    rules:
      - alert: ContainerKilled
        expr: probe_success != 1
        labels:
          alert_level: critical
        for: 1m
        annotations:
          description: 'tcp probe failed for container: {{ $labels.group }}, address: {{ $labels.instance }}'
          summary: 'container: {{ $labels.group }}, address: {{ $labels.instance }} unreachable'
      - alert: NodeHighCpuUsage
        expr: (1 - sum(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance)) * 100 > 80
        labels:
          alert_level: warning
        for: 1m
        annotations:
          description: '{{ $labels.instance }} cpu usage is above 80%, current value: {{ $value }}'
          summary: '{{ $labels.instance }}: High Cpu Usage detected.'
      - alert: NodeMemoryCpuUsage
        expr: (1 - sum(node_memory_MemAvailable_bytes) by(instance) / sum(node_memory_MemTotal_bytes) by(instance)) * 100 > 80
        labels:
          alert_level: warning
        for: 1m
        annotations:
          description: '{{ $labels.instance }} memory usage is above 80%, current value: {{ $value }}'
          summary: '{{ $labels.instance }}: High Memory Usage detected.'
