# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: build-service
    main: ./cmd
    binary: bin/hdt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X https://github.com/hstreamdb/deployment-tool/pkg/version.RELEASE={{ .Tag }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version  }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"