global:
  # Mark the alarm status as resolved when alertmanager has not received an alarm
  # for a certain amount of time
  resolve_timeout: 5m

route:
  # A default receiver
  receiver: "default"

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ["instance"]

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 3m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1h

  routes:
#    - receiver: 'slack-notifier'
#      continue: true
#    - receiver: 'phone-call'
#      matchers:
#        - alert_level = "critical"

receivers:
  - name: 'slack-notifier'
    slack_configs:
      - api_url: ''
        channel: '#hstream-notification'
        username: 'hstream-alert'
        icon_emoji: ':bell:'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts -}}
          *Summary:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          
          *Description:* {{ .Annotations.description }}
          
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        send_resolved: true

  - name: 'phone-call'
    webhook_configs:
      - url: ''
        send_resolved: true

  # This doesn't alert anything, please configure your own receiver
  - name: "default"
