global:
  # # Username to login via SSH
  user: "root"
  # # The path of SSH identity file
  # key_path: "~/.ssh/hstream-aliyun.pem"
  # # SSH service monitor port
  ssh_port: 22
  # # Unique identification of the cluster
  cluster_id: "hstreamdb"
  # # Replication factors of store metadata
  # meta_replica: 1
  # # Local path to MetaStore config file
  # meta_store_config_path: ""
  # # Local path to HStore config file
  # hstore_config_path: ""
  # # HStore config file can be loaded from network filesystem, for example, the config file
  # # can be stored in meta store and loaded via network request. Set this option to true will
  # # force store load config file from its local filesystem.
  # disable_store_network_config_path: true
  # # Local path to HServer config file
  # hserver_config_path: ""
  # # use grpc-haskell framework
  # enable_grpc_haskell: false
  # # Local path to ElasticSearch config file
  # elastic_search_config_path: ""
  # # Only enable for linux kernel which support dscp reflection(linux kernel version
  # # greater and equal than 4.x)
  # enable_dscp_reflection: false
  # # When set to true, hdt won't start any node_exporter or cadvisor instance
  # disable_monitor_suite: false
  # # Global container configuration, can be updated by each component's container_config field.
  # # Note for options field, the component's options field will overwrite the global's
  # container_config:
    # cpu_limit: 2.00
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true
    # options: ""

monitor:
  # # Node exporter port
  node_exporter_port: 9100
  # # Node exporter image
  # node_exporter_image: "prom/node-exporter"
  # # Cadvisor port
  cadvisor_port: 7000
  # # Cadvisor image
  # cadvisor_image: "gcr.io/cadvisor/cadvisor:v0.39.3"
  # # List of nodes that won't be monitored.
  # excluded_hosts: []
  # # root directory for all monitor related config files.
  # remote_config_path: "/home/deploy/monitor"
  # # root directory for all monitor related data files.
  # data_dir: "/home/deploy/data/monitor"
  # # Global container configuration for monitor stacks.
  # container_config:
    # cpu_limit: 2.00
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true
    # options: ""

hserver:
  - host: 10.1.0.10
    # # HServer docker image
    # image: "hstreamdb/hstream"
    # # The listener is an adderss that a server advertises to its clients so they can connect to the server.
    # # Each listener is specified as "listener_name:hstream://host_name:port_number". The listener_name is
    # # a name that identifies the listener, and the "host_name" and "port_number" are the IP address and
    # # port number that reachable from the client's network. Multi listener will split by comma.
    # # For example: public_ip:hstream://39.101.190.70:6582
    # advertised_listener: ""
    # # HServer listen port
    # port: 6570
    # # HServer internal port
    # internal_port: 6571
    # # HServer start parameter
    server_param:
      # HServer log level, valid values: [critical|error|warning|notify|info|debug]
      log-level: info
      # HStore log level, valid values: [critical|error|warning|notify|info|debug|spew]
      store-log-level: info
      # Specific tls related param
      # tls-key-path: /path/to/the/server.key.pem
      # tls-cert-path: /path/to/the/signed.server.cert.pem
      # tls-ca-path: /path/to/the/ca.cert.pem
      # enable-tls: true
    # # Root directory of HServer config files
    # remote_config_path: "/home/deploy/hserver"
    # # Root directory of HServer data files
    # data_dir: "/home/deploy/data/hserver"
    # # HServer container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
  - host: 10.1.0.11
    # # HServer docker image
    # image: "hstreamdb/hstream"
    # # The listener is an adderss that a server advertises to its clients so they can connect to the server.
    # # Each listener is specified as "listener_name:hstream://host_name:port_number". The listener_name is
    # # a name that identifies the listener, and the "host_name" and "port_number" are the IP address and
    # # port number that reachable from the client's network. Multi listener will split by comma.
    # # For example: public_ip:hstream://39.101.190.71:6582
    # advertised_listener: ""
    # # HServer listen port
    # port: 6570
    # # HServer internal port
    # internal_port: 6571
    # # HServer start parameter
    server_param:
      # HServer log level, valid values: [critical|error|warning|notify|info|debug]
      log-level: info
      # HStore log level, valid values: [critical|error|warning|notify|info|debug|spew]
      store-log-level: info
      # Specific tls related param
      # tls-key-path: /path/to/the/server.key.pem
      # tls-cert-path: /path/to/the/signed.server.cert.pem
      # tls-ca-path: /path/to/the/ca.cert.pem
      # enable-tls: true
    # # Root directory of HServer config files
    # remote_config_path: "/home/deploy/hserver"
    # # Root directory of HServer data files
    # data_dir: "/home/deploy/data/hserver"
    # # HServer container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
  - host: 10.1.0.12
    # # HServer docker image
    # image: "hstreamdb/hstream"
    # # The listener is an adderss that a server advertises to its clients so they can connect to the server.
    # # Each listener is specified as "listener_name:hstream://host_name:port_number". The listener_name is
    # # a name that identifies the listener, and the "host_name" and "port_number" are the IP address and
    # # port number that reachable from the client's network. Multi listener will split by comma.
    # # For example: public_ip:hstream://39.101.190.72:6582
    # advertised_listener: ""
    # # HServer listen port
    # port: 6570
    # # HServer internal port
    # internal_port: 6571
    # # HServer start parameter
    server_param:
      # HServer log level, valid values: [critical|error|warning|notify|info|debug]
      log-level: info
      # HStore log level, valid values: [critical|error|warning|notify|info|debug|spew]
      store-log-level: info
      # Specific tls related param
      # tls-key-path: /path/to/the/server.key.pem
      # tls-cert-path: /path/to/the/signed.server.cert.pem
      # tls-ca-path: /path/to/the/ca.cert.pem
      # enable-tls: true
    # # Root directory of HServer config files
    # remote_config_path: "/home/deploy/hserver"
    # # Root directory of HServer data files
    # data_dir: "/home/deploy/data/hserver"
    # # HServer container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

hadmin:
  - host: 10.1.0.10
    # # HAdmin docker image
    # image: "hstreamdb/hstream"
    # # HAdmin listen port
    # port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hadmin"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/hadmin"
    # # HStore container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

hstore:
  - host: 10.1.0.10
    # # HStore docker image
    # image: "hstreamdb/hstream"
    # # HStore listen port
    # port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hstore"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/store"
    # # Total used disks
    # disk: 1
    # # Total shards
    # shards: 2
    # # The role of the HStore instance.
    # role: "Both" # [Storage|Sequencer|Both]
    # # When Enable_admin is turned on, the instance can receive and process admin requests
    enable_admin: true
    # # HStore container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
  - host: 10.1.0.11
    # # HStore docker image
    # image: "hstreamdb/hstream"
    # # HStore listen port
    # port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hstore"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/store"
    # # Total used disks
    # disk: 1
    # # Total shards
    # shards: 2
    # # The role of the HStore instance.
    # role: "Both" # [Storage|Sequencer|Both]
    # # HStore container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
  - host: 10.1.0.12
    # # HStore docker image
    # image: "hstreamdb/hstream"
    # # HStore listen port
    # port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hstore"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/store"
    # # Total used disks
    # disk: 1
    # # Total shards
    # shards: 2
    # # The role of the HStore instance.
    # role: "Both" # [Storage|Sequencer|Both]
    # # HStore container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

meta_store:
  - host: 10.1.0.10
    # # Meta-Store docker image
    # image: "zookeeper:3.6"
    # # Meta-Store listen port
    # port: 2181
    # # Raft port used by rqlite
    # raft_port: 4002
    # # Root directory of Meta-Store config files
    # remote_config_path: "/home/deploy/metastore"
    # # Root directory of Meta-Store data files
    # data_dir: "/home/deploy/data/metastore"
    # # Meta-Store container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: '-e JVMFLAGS="-Xmx4096m"'
  - host: 10.1.0.11
    # # Meta-Store docker image
    # image: "zookeeper:3.6"
    # # Meta-Store listen port
    # port: 2181
    # # Raft port used by rqlite
    # raft_port: 4002
    # # Root directory of Meta-Store config files
    # remote_config_path: "/home/deploy/metastore"
    # # Root directory of Meta-Store data files
    # data_dir: "/home/deploy/data/metastore"
    # # Meta-Store container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: '-e JVMFLAGS="-Xmx4096m"'
  - host: 10.1.0.12
    # # Meta-Store docker image
    # image: "zookeeper:3.6"
    # # Meta-Store listen port
    # port: 2181
    # # Raft port used by rqlite
    # raft_port: 4002
    # # Root directory of Meta-Store config files
    # remote_config_path: "/home/deploy/metastore"
    # # Root directory of Meta-Store data files
    # data_dir: "/home/deploy/data/metastore"
    # # Meta-Store container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: '-e JVMFLAGS="-Xmx4096m"'

hstream_console:
  - host: 10.1.0.15
    # # HStream-console image
    # image: "hstreamdb/hstream-console"
    # # HStream-console service monitor port
    # port: 5177
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

http_server:
  - host: 10.1.0.15
    # # Http_Server docker image
    # image: "hstreamdb/http-server"
    # # Http_Server service monitor port
    # port: 8081
    # # Root directory of Http_Server config files
    # remote_config_path: "/home/deploy/http-server"
    # # Root directory of Http_Server data files
    # data_dir: "/home/deploy/data/http-server"
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

blackBox:
  - host: 10.1.0.15
    # # BlackBox docker image
    # image: "prom/blackbox-exporter"
    # # BlackBox service monitor port
    # port: 9115
    # # Root directory of BlackBox config files
    # remote_config_path: "/home/deploy/blackbox"
    # # Root directory of BlackBox data files
    # data_dir: "/home/deploy/data/blackbox"
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

prometheus:
  - host: 10.1.0.15
    # # Prometheus docker image
    # image: "prom/prometheus"
    # # Prometheus service monitor port
    # port: 9090
    # # Root directory of Prometheus config files
    # remote_config_path: "/home/deploy/prometheus"
    # # Root directory of Prometheus data files
    # data_dir: "/home/deploy/data/prometheus"
    # # prometheus data retention time, default is 15 days.
    retention_time: "15d"
    # # Prometheus container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

grafana:
  - host: 10.1.0.15
    # # Grafana docker image
    # image: "grafana/grafana-oss:main"
    # # Grafana service monitor port
    # port: 3000
    # # Root directory of Grafana config files
    # remote_config_path: "/home/deploy/grafana"
    # # Root directory of Grafana data files
    # data_dir: "/home/deploy/data/grafana"
    # # Set up grafana without login
    disable_login: true
    # # Grafana container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

alertmanager:
  - host: 10.0.1.15
    # # Alertmanager docker image
    # image: "prom/alertmanager"
    # # Alertmanager service monitor port
    # port: 9093
    # # Root directory of Alertmanager config files
    # remote_config_path: "/home/deploy/alertmanager"
    # # Root directory of Alertmanager data files
    # data_dir: "/home/deploy/data/alertmanager"
    # # Alertmanager container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

hstream_exporter:
  - host: 10.1.0.15
    # # HStream_Exporter docker image
    # image: "hstreamdb/hstream-exporter"
    # # HStream_Exporter service monitor port
    # port: 9250
    # # HStream_Exporter log leve: [debug|info|warning|error|fatal|panic]
    # log_level: info
    # # Root directory of HStream_Exporter config files
    # remote_config_path: "/home/deploy/hstream-exporter"
    # # Root directory of HStream_Exporter data files
    # data_dir: "/home/deploy/data/hstream-exporter"
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

elasticsearch:
  - host: 10.1.0.15
    # # Elasticsearch service monitor port
    # port: 9200
    # # Elasticsearch docker image
    # image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    # image: "docker.elastic.co/elasticsearch/elasticsearch:8.5.0"
    # # Root directory of Elasticsearch config files
    # remote_config_path: "/home/deploy/elasticsearch"
    # # Root directory of Elasticsearch data files
    # data_dir: "/home/deploy/data/elasticsearch"
    # # Elasticsearch container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

kibana:
  - host: 10.1.0.15
    # # Kibana service monitor port
    # port: 5601
    # # Kibana docker image
    # image: "docker.elastic.co/kibana/kibana-oss:7.10.2"
    # image: "docker.elastic.co/kibana/kibana:8.5.0"
    # # Root directory of Kibana config files
    # remote_config_path: "/home/deploy/kibana"
    # # Root directory of Kibana data files
    # data_dir: "/home/deploy/data/kibana"
    # # Kibana container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""

filebeat:
  # # The ip address of Filebeats
  - host: 10.1.0.10
    # # Filebeat docker image
    # image: "docker.elastic.co/beats/filebeat-oss:7.10.2"
    # image: "docker.elastic.co/beats/filebeat:8.5.0"
    # # Root directory of Filebeat config files
    # remote_config_path: "/home/deploy/filebeat"
    # # Root directory of Filebeat data files
    # data_dir: "/home/deploy/data/filebeat"
    # # Filebeat container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
  - host: 10.1.0.11
    # # Filebeat docker image
    # image: "docker.elastic.co/beats/filebeat-oss:7.10.2"
    # image: "docker.elastic.co/beats/filebeat:8.5.0"
    # # Root directory of Filebeat config files
    # remote_config_path: "/home/deploy/filebeat"
    # # Root directory of Filebeat data files
    # data_dir: "/home/deploy/data/filebeat"
    # # Filebeat container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
  - host: 10.1.0.12
    # # Filebeat docker image
    # image: "docker.elastic.co/beats/filebeat-oss:7.10.2"
    # image: "docker.elastic.co/beats/filebeat:8.5.0"
    # # Root directory of Filebeat config files
    # remote_config_path: "/home/deploy/filebeat"
    # # Root directory of Filebeat data files
    # data_dir: "/home/deploy/data/filebeat"
    # # Filebeat container configuration
    # container_config:
      # cpu_limit: 2.00
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
      # options: ""
