global:
  # # Username to login via SSH
  user: "root"
  # # The path of SSH identity file
  # key_path: "~/.ssh/hstream-aliyun.pem"
  # # SSH service monitor port
  ssh_port: 22
  # # Replication factors of store metadata
  # meta_replica: 3
  # # Local path to MetaStore config file
  # meta_store_config_path: ""
  # # Local path to HStore config file
  # hstore_config_path: ""
  # # HStore config file can be loaded from network filesystem, for example, the config file
  # # can be stored in meta store and loaded via network request. Set this option to true will
  # # force store load config file from its local filesystem.
  # disable_store_network_config_path: true
  # # Local path to HServer config file
  # hserver_config_path: ""
  # # Global container configuration
  # container_config:
    # cpu_limit: 200
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true

monitor:
  # # Node exporter port
  node_exporter_port: 9100
  # # Node exporter image
  # node_exporter_image: "prom/node-exporter"
  # # Cadvisor port
  cadvisor_port: 7000
  # # Cadvisor image
  # cadvisor_image: "gcr.io/cadvisor/cadvisor:v0.39.3"
  # # List of nodes that won't be monitored.
  # excluded_hosts: []
  # # root directory for all monitor related config files.
  # remote_config_path: "/home/deploy/monitor"
  # # root directory for all monitor related data files.
  # data_dir: "/home/deploy/data/monitor"
  # # Set up grafana without login
  grafana_disable_login: true
  # # Global container configuration for monitor stacks.
  # container_config:
    # cpu_limit: 200
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true

hserver:
  # # The ip address of the HServer
  - host: 10.1.0.10
    # # HServer docker image
    # image: "hstreamdb/hstream"
    # # HServer listen port
    # port: 6570
    # # HServer internal port
    # internal_port: 6571
    # # HServer configuration
    # server_config:
      # # HServer log level, valid values: [critical|error|warning|notify|info|debug]
      # server_log_level: info
      # # HStore log level, valid values: [critical|error|warning|notify|info|debug|spew]
      # store_log_level: info
      # # Specific server compression algorithm, valid values: [none|lz4|lz4hc]
      # compression: lz4
    # # Root directory of HServer config files
    # remote_config_path: "/home/deploy/hserver"
    # # Root directory of HServer data files
    # data_dir: "/home/deploy/data/hserver"
    # # HServer container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.11
    # # HServer docker image
    # image: "hstreamdb/hstream"
    # # HServer listen port
    # port: 6570
    # # HServer internal port
    # internal_port: 6571
    # # HServer configuration
    # server_config:
      # # HServer log level, valid values: [critical|error|warning|notify|info|debug]
      # server_log_level: info
      # # HStore log level, valid values: [critical|error|warning|notify|info|debug|spew]
      # store_log_level: info
      # # Specific server compression algorithm, valid values: [none|lz4|lz4hc]
      # compression: lz4
    # # Root directory of HServer config files
    # remote_config_path: "/home/deploy/hserver"
    # # Root directory of HServer data files
    # data_dir: "/home/deploy/data/hserver"
    # # HServer container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.12
    # # HServer docker image
    # image: "hstreamdb/hstream"
    # # HServer listen port
    # port: 6570
    # # HServer internal port
    # internal_port: 6571
    # # HServer configuration
    # server_config:
      # # HServer log level, valid values: [critical|error|warning|notify|info|debug]
      # server_log_level: info
      # # HStore log level, valid values: [critical|error|warning|notify|info|debug|spew]
      # store_log_level: info
      # # Specific server compression algorithm, valid values: [none|lz4|lz4hc]
      # compression: lz4
    # # Root directory of HServer config files
    # remote_config_path: "/home/deploy/hserver"
    # # Root directory of HServer data files
    # data_dir: "/home/deploy/data/hserver"
    # # HServer container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true

hstore:
  - host: 10.1.0.10
    # # HStore docker image
    # image: "hstreamdb/hstream"
    # # HStore admin port
    # admin_port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hstore"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/store"
    # # Total used disks
    # disk: 1
    # # Total shards
    # shards: 2
    # # The role of the HStore instance.
    # role: "Both" # [Storage|Sequencer|Both]
    # # When Enable_admin is turned on, the instance can receive and process admin requests
    enable_admin: true
    # # HStore container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.11
    # # HStore docker image
    # image: "hstreamdb/hstream"
    # # HStore admin port
    # admin_port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hstore"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/store"
    # # Total used disks
    # disk: 1
    # # Total shards
    # shards: 2
    # # The role of the HStore instance.
    # role: "Both" # [Storage|Sequencer|Both]
    # # HStore container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.12
    # # HStore docker image
    # image: "hstreamdb/hstream"
    # # HStore admin port
    # admin_port: 6440
    # # Root directory of HStore config files
    # remote_config_path: "/home/deploy/hstore"
    # # Root directory of HStore data files
    # data_dir: "/home/deploy/data/store"
    # # Total used disks
    # disk: 1
    # # Total shards
    # shards: 2
    # # The role of the HStore instance.
    # role: "Both" # [Storage|Sequencer|Both]
    # # HStore container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true

meta_store:
  - host: 10.1.0.10
    # # Meta-store docker image
    # image: "zookeeper:3.6"
    # # Meta-store port, currently only works for rqlite. zk will
    # # monitor on 4001
    # port: 4001
    # # Raft port used by rqlite
    # raft_port: 4002
    # # Root directory of Meta-Store config files
    # remote_config_path: "/home/deploy/metastore"
    # # Root directory of Meta-store data files
    # data_dir: "/home/deploy/data/metastore"
    # # Meta-store container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.11
    # # Meta-store docker image
    # image: "zookeeper:3.6"
    # # Meta-store port, currently only works for rqlite. zk will
    # # monitor on 2181
    # port: 4001
    # # Raft port used by rqlite
    # raft_port: 4002
    # # Root directory of Meta-Store config files
    # remote_config_path: "/home/deploy/metastore"
    # # Root directory of Meta-store data files
    # data_dir: "/home/deploy/data/metastore"
    # # Meta-store container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.12
    # # Meta-store docker image
    # image: "zookeeper:3.6"
    # # Meta-store port, currently only works for rqlite. zk will
    # # monitor on 2181
    # port: 4001
    # # Raft port used by rqlite
    # raft_port: 4002
    # # Root directory of Meta-Store config files
    # remote_config_path: "/home/deploy/metastore"
    # # Root directory of Meta-store data files
    # data_dir: "/home/deploy/data/metastore"
    # # Meta-store container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true

http_server:
  - host: 10.1.0.15
    # # Http_server docker image
    # image: "hstreamdb/http-server"
    # # Http_server service monitor port
    # port: 8081
    # # Root directory of http_server config files
    # remote_config_path: "/home/deploy/http-server"
    # # Root directory of http_server data files
    # data_dir: "/home/deploy/data/http-server"
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true

prometheus:
  - host: 10.1.0.15
    # # Prometheus docker image
    # image: "prom/prometheus"
    # # Prometheus service monitor port
    # port: 9090
    # # Root directory of Prometheus config files
    # remote_config_path: "/home/deploy/prometheus"
    # # Root directory of Prometheus data files
    # data_dir: "/home/deploy/data/prometheus"
    # # Prometheus container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true

grafana:
  - host: 10.1.0.15
    # # Grafana docker image
    # image: "grafana/grafana-oss:main"
    # # Grafana service monitor port
    # port: 3000
    # # Root directory of Grafana config files
    # remote_config_path: "/home/deploy/grafana"
    # # Root directory of Grafana data files
    # data_dir: "/home/deploy/data/grafana"
    # # Grafana container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true

# # Server configs are used to specify the configuration of Alertmanager Servers.
alertmanager:
  # # The ip address of the Alertmanager Server.
  - host: 10.0.1.15
  # # Alertmanager docker image
  # image: "prom/alertmanager"
  # # Alertmanager service monitor port
  # port: 9093
  # # Root directory of Alertmanager config files
  # remote_config_path: "/home/deploy/alertmanager"
  # # Root directory of Alertmanager data files
  # data_dir: "/home/deploy/data/alertmanager"
  # # Alertmanager container configuration
  # container_config:
    # cpu_limit: 200
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true

hstream_exporter:
  - host: 10.1.0.15
  # # hstream_exporter docker image
  # image: "hstreamdb/hstream-exporter"
  # # hstream_exporter service monitor port
  # port: 9200
  # # Root directory of hstream_exporter config files
  # remote_config_path: "/home/deploy/hstream-exporter"
  # # Root directory of hstream_exporter data files
  # data_dir: "/home/deploy/data/hstream-exporter"
  # container_config:
    # cpu_limit: 200
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true

elasticsearch:
  - host: 10.1.0.15
  # # Elasticsearch docker image
  # image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.3"
  # # Elasticsearch container configuration
  # container_config:
    # cpu_limit: 200
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true

kibana:
  - host: 10.1.0.15
  # # Kibana docker image
  # image: "docker.elastic.co/kibana/kibana:8.4.3"
  # # Kibana container configuration
  # container_config:
    # cpu_limit: 200
    # memory_limit: 8G
    # disable_restart: true
    # remove_when_exit: true

filebeat:
  # # The ip address of Filebeats
  - host: 10.1.0.10
    # # Filebeat docker image
    # image: "docker.elastic.co/beats/filebeat:8.4.3"
    # # Root directory of Filebeat config files
    # remote_config_path: "/home/deploy/filebeat"
    # # Filebeat container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.11
    # # Filebeat docker image
    # image: "docker.elastic.co/beats/filebeat:8.4.3"
    # # Root directory of Filebeat config files
    # remote_config_path: "/home/deploy/filebeat"
    # # Filebeat container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
  - host: 10.1.0.12
    # # Filebeat docker image
    # image: "docker.elastic.co/beats/filebeat:8.4.3"
    # # Root directory of Filebeat config files
    # remote_config_path: "/home/deploy/filebeat"
    # # Filebeat container configuration
    # container_config:
      # cpu_limit: 200
      # memory_limit: 8G
      # disable_restart: true
      # remove_when_exit: true
