{
 "title": "HStream Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(up{group=\"node_exporter\"}, instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m" },
   { "name": "clusterId", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$host\", cluster=~\"$clusterId\"} - 0",
     "legendFormat": "HostName"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$host\", cluster=~\"$clusterId\"})by(instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\", cluster=~\"$clusterId\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$host\", mode='system', cluster=~\"$clusterId\"}) by (instance)",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "node_load5{instance=~\"$host\", cluster=~\"$clusterId\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$host\", mode=\"idle\", cluster=~\"$clusterId\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$host\", cluster=~\"$clusterId\"} / (node_memory_MemTotal_bytes{instance=~\"$host\", cluster=~\"$clusterId\"})))* 100",
     "legendFormat": "Memory used%"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"$host\",cluster=~\"$clusterId\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$host\",cluster=~\"$clusterId\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {instance=~\"$host\",cluster=~\"$clusterId\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{instance=~\"$host\",cluster=~\"$clusterId\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$host\",cluster=~\"$clusterId\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partition used%"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{instance=~\"$host\",cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Disk read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{instance=~\"$host\",cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Disk write"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$host\",cluster=~\"$clusterId\"} - 0",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$host\",cluster=~\"$clusterId\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{instance=~\"$host\",cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Stream Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "AppendSpeed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_stream_append_in_bytes{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by(server_host)",
       "legendFormat": "{{server_host}}-append"
      },
      {
       "expr": "sum(irate(hstream_exporter_stream_append_in_bytes{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-append-speed"
      }
     ]
    },
    {
     "title": "AppendQPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_stream_append_total{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host)",
       "legendFormat": "{{server_host}}-qps"
      },
      {
       "expr": "sum(irate(hstream_exporter_stream_append_total{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-qps"
      }
     ]
    },
    {
     "title": "AppendRequestLatency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "hstream_exporter_stream_append_latency{server_host=~\"$host\", cluster=~\"$clusterId\"}",
       "legendFormat": "{{server_host}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "FailedAppendPersentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(hstream_exporter_stream_append_failed{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host) / sum(rate(hstream_exporter_stream_append_total{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host) * 100",
       "legendFormat": "{{server_host}}"
      },
      {
       "expr": "sum(rate(hstream_exporter_stream_append_failed{cluster=~\"$clusterId\"}[$interval])) / sum(rate(hstream_exporter_stream_append_total{cluster=~\"$clusterId\"}[$interval])) * 100",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "StreamReadSpeed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_stream_read_in_bytes{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by(server_host)",
       "legendFormat": "{{server_host}}-read"
      },
      {
       "expr": "sum(irate(hstream_exporter_stream_read_in_bytes{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-read-speed"
      }
     ]
    },
    {
     "title": "StreamReadLatency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "hstream_exporter_stream_read_latency{server_host=~\"$host\", cluster=~\"$clusterId\"}",
       "legendFormat": "{{server_host}}-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscription Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SubSendSpeed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_subscription_send_out_bytes{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host)",
       "legendFormat": "{{server_host}}-send-speed"
      },
      {
       "expr": "sum(irate(hstream_exporter_subscription_send_out_bytes{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-send-speed"
      }
     ]
    },
    {
     "title": "SubAck",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_subscription_received_acks{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host)",
       "legendFormat": "{{server_host}}-ack"
      },
      {
       "expr": "sum(irate(hstream_exporter_subscription_received_acks{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-ack"
      }
     ]
    },
    {
     "title": "SubscriptionRequestQPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_subscription_request_messages{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host)",
       "legendFormat": "{{server_host}}-sub-req"
      },
      {
       "expr": "sum(irate(hstream_exporter_subscription_request_messages{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-sub-req"
      }
     ]
    },
    {
     "title": "SubscriptionResponsetQPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_subscription_response_messages{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host)",
       "legendFormat": "{{server_host}}-sub-response"
      },
      {
       "expr": "sum(irate(hstream_exporter_subscription_response_messages{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-sub-response"
      }
     ]
    },
    {
     "title": "SubResend",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(hstream_exporter_subscription_resend_records{server_host=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (server_host)",
       "legendFormat": "{{server_host}}-sub-resend"
      },
      {
       "expr": "sum(irate(hstream_exporter_subscription_resend_records{cluster=~\"$clusterId\"}[$interval]))",
       "legendFormat": "total-resend"
      }
     ]
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node CPU Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", mode=\"idle\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)) * 100",
     "legendFormat": "{{instance}}-total"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", mode=\"system\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}-system"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", mode=\"user\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}-user"
    }
   ]
  },
  {
   "title": "Node Memory Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{instance=~\"$host\", cluster=~\"$clusterId\"}) by(instance) / sum(node_memory_MemTotal_bytes{instance=~\"$host\", cluster=~\"$clusterId\"}) by(instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node NetWork Transmit Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_network_transmit_queue_length{instance=~\"$host\", cluster=~\"$clusterId\"}",
     "legendFormat": "{{instance}} - {{ device }} -   Interface transmit queue length"
    }
   ]
  },
  {
   "title": "Node Sockstat TCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$host\", cluster=~\"$clusterId\"}",
     "legendFormat": "{{instance}}_TCP_alloc - Allocated sockets"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$host\", cluster=~\"$clusterId\"}",
     "legendFormat": "{{instance}}_TCP_inuse - Tcp sockets currently in use"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=~\"$host\", cluster=~\"$clusterId\"}",
     "legendFormat": "{{instance}}_TCP_orphan - Orphan sockets"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$host\", cluster=~\"$clusterId\"}",
     "legendFormat": "{{instance}}_TCP_tw - Sockets waiting close"
    }
   ]
  },
  {
   "title": "Node Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_network_receive_bytes_total{instance=~\"$host\", cluster=~\"$clusterId\", device=~\"eth.*\"}[$interval]))",
     "legendFormat": "{{instance}}-receive"
    },
    {
     "expr": "sum by(instance) (irate(node_network_transmit_bytes_total{instance=~\"$host\", cluster=~\"$clusterId\", device=~\"eth.*\"}[$interval]))",
     "legendFormat": "{{instance}}-transmit"
    }
   ]
  },
  {
   "title": "Node Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_ IO time"
    }
   ]
  },
  {
   "title": "Node Disk Read Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-write"
    }
   ]
  },
  {
   "title": "Node Disk R/W Time",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance) / sum(rate(node_disk_reads_completed_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_read time"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{instance=~\"$host\"}[$interval])) by (instance) / sum(rate(node_disk_writes_completed_total{instance=~\"$host\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_write time"
    }
   ]
  },
  {
   "title": "Node Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_Reads completed"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}_Writes completed"
    }
   ]
  },
  {
   "title": "Node Disk Average Queue Size",
   "type": "timeseries",
   "description": "The average queue length of the requests that were issued to the device",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  { "title": "Components Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Container CPU Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", name=\"deploy_hserver\"}[$interval])) BY (instance, name) * 100)",
     "legendFormat": "{{instance}}-server"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", name=\"deploy_hstore\"}[$interval])) BY (instance, name) * 100)",
     "legendFormat": "{{instance}}-store"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", name=\"deploy_meta\"}[$interval])) BY (instance, name) * 100)",
     "legendFormat": "{{instance}}-meta"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster=~\"$clusterId\", name=~\"IOTASK.*\"}[$interval])) BY (instance, name) * 100)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster=~\"$clusterId\", name=\"deploy_hserver\"}) BY (instance, name))",
     "legendFormat": "{{instance}}-server"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster=~\"$clusterId\", name=\"deploy_hstore\"}) BY (instance, name))",
     "legendFormat": "{{instance}}-store"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster=~\"$clusterId\", name=\"deploy_meta\"}) BY (instance, name))",
     "legendFormat": "{{instance}}-meta"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster=~\"$clusterId\", name=~\"IOTASK.*\"}) BY (instance, name))",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  }
 ]
}