{
 "title": "HStream Kafka Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(up{group=\"node_exporter\"}, instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m" },
   { "name": "clusterId", "query": { "query": "label_values(cluster_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$host\", cluster_id=~\"$clusterId\"} - 0",
     "legendFormat": "HostName"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$host\", cluster_id=~\"$clusterId\"})by(instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$host\", mode='system', cluster_id=~\"$clusterId\"}) by (instance)",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "node_load5{instance=~\"$host\", cluster_id=~\"$clusterId\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$host\", mode=\"idle\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\"} / (node_memory_MemTotal_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\"})))* 100",
     "legendFormat": "Memory used%"
    },
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"$host\",cluster_id=~\"$clusterId\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$host\",cluster_id=~\"$clusterId\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {instance=~\"$host\",cluster_id=~\"$clusterId\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{instance=~\"$host\",cluster_id=~\"$clusterId\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$host\",cluster_id=~\"$clusterId\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Partition used%"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{instance=~\"$host\",cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Disk read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{instance=~\"$host\",cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Disk write"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$host\",cluster_id=~\"$clusterId\"} - 0",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$host\",cluster_id=~\"$clusterId\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{instance=~\"$host\",cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(total_requests{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-qps"
    },
    {
     "expr": "sum(irate(total_requests{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total-qps"
    }
   ]
  },
  {
   "title": "RequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(instance, le) (rate(handler_latency_bucket[1m])))",
     "legendFormat": "{{instance}}-p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(instance, le) (rate(handler_latency_bucket[1m])))",
     "legendFormat": "{{instance}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(instance, le) (rate(handler_latency_bucket[1m])))",
     "legendFormat": "{{instance}}-p99"
    }
   ]
  },
  {
   "title": "HandlerLatencyDetail",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(instance, le, handler) (rate(handler_latency_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(instance, le, handler) (rate(handler_latency_bucket[1m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(instance, le, handler) (rate(handler_latency_bucket[1m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Stream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "AppendSpeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(topic_bytes_in{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by(instance)",
     "legendFormat": "{{instance}}-append"
    },
    {
     "expr": "sum(irate(topic_bytes_in{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total-append-speed"
    }
   ]
  },
  {
   "title": "AppendQPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(total_produce_request{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-qps"
    },
    {
     "expr": "sum(irate(total_produce_request{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total-qps"
    }
   ]
  },
  {
   "title": "AppendRequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(instance, le) (rate(topic_append_latency_bucket[1m])))",
     "legendFormat": "{{instance}}-p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(instance, le) (rate(topic_append_latency_bucket[1m])))",
     "legendFormat": "{{instance}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(instance, le) (rate(topic_append_latency_bucket[1m])))",
     "legendFormat": "{{instance}}-p99"
    }
   ]
  },
  {
   "title": "AppendMessageRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(irate(topic_messages_in{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-qps"
    },
    {
     "expr": "sum(irate(topic_messages_in{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total-qps"
    }
   ]
  },
  {
   "title": "FailedAppendPersentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(total_failed_produce_request{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance) / sum(rate(total_produce_request{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{server_host}}"
    },
    {
     "expr": "sum(rate(total_failed_produce_request{cluster_id=~\"$clusterId\"}[$interval])) / sum(rate(total_produce_request{cluster_id=~\"$clusterId\"}[$interval])) * 100",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Subscription Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "SubSendSpeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(topic_bytes_out{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-send-speed"
    },
    {
     "expr": "sum(irate(topic_bytes_out{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total-send-speed"
    }
   ]
  },
  {
   "title": "SubMessageSpeed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(irate(topic_messages_out{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(topic_messages_out{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "SubscriptionRequestQPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(total_consume_request{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}-sub-req"
    },
    {
     "expr": "sum(irate(total_consume_request{cluster_id=~\"$clusterId\"}[$interval]))",
     "legendFormat": "total-sub-req"
    }
   ]
  },
  {
   "title": "TopicReadLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(instance, le) (rate(topic_read_latency_bucket[5m])))",
     "legendFormat": "{{instance}}-p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(instance, le) (rate(topic_read_latency_bucket[5m])))",
     "legendFormat": "{{instance}}-p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(instance, le) (rate(topic_read_latency_bucket[5m])))",
     "legendFormat": "{{instance}}-p99"
    }
   ]
  },
  {
   "title": "CommitOffsets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "consumer_group_committed_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Used Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", mode=\"idle\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)) * 100",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", mode=\"system\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance) * 100",
       "legendFormat": "{{instance}}-system"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", mode=\"user\"}[$interval])) by (instance) / sum(rate(node_cpu_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance) * 100",
       "legendFormat": "{{instance}}-user"
      }
     ]
    },
    {
     "title": "Node Memory Used Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - sum(node_memory_MemAvailable_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\"}) by(instance) / sum(node_memory_MemTotal_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\"}) by(instance)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node NetWork Transmit Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{instance=~\"$host\", cluster_id=~\"$clusterId\"}",
       "legendFormat": "{{instance}} - {{ device }} -   Interface transmit queue length"
      }
     ]
    },
    {
     "title": "Node Sockstat TCP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$host\", cluster_id=~\"$clusterId\"}",
       "legendFormat": "{{instance}}_TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~\"$host\", cluster_id=~\"$clusterId\"}",
       "legendFormat": "{{instance}}_TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=~\"$host\", cluster_id=~\"$clusterId\"}",
       "legendFormat": "{{instance}}_TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$host\", cluster_id=~\"$clusterId\"}",
       "legendFormat": "{{instance}}_TCP_tw - Sockets waiting close"
      }
     ]
    },
    {
     "title": "Node Network Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_network_receive_bytes_total{instance=~\"$host\", cluster_id=~\"$clusterId\", device=~\"eth.*\"}[$interval]))",
       "legendFormat": "{{instance}}-receive"
      },
      {
       "expr": "sum by(instance) (irate(node_network_transmit_bytes_total{instance=~\"$host\", cluster_id=~\"$clusterId\", device=~\"eth.*\"}[$interval]))",
       "legendFormat": "{{instance}}-transmit"
      }
     ]
    },
    {
     "title": "Node Time Spent Doing I/Os",
     "type": "timeseries",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}_ IO time"
      }
     ]
    },
    {
     "title": "Node Disk Read Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}-read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}-write"
      }
     ]
    },
    {
     "title": "Node Disk R/W Time",
     "type": "timeseries",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_time_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance) / sum(rate(node_disk_reads_completed_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}_read time"
      },
      {
       "expr": "sum(rate(node_disk_write_time_seconds_total{instance=~\"$host\"}[$interval])) by (instance) / sum(rate(node_disk_writes_completed_total{instance=~\"$host\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}_write time"
      }
     ]
    },
    {
     "title": "Node Disk IOps Completed（IOPS）",
     "type": "timeseries",
     "description": "Read/write completions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}_Reads completed"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$interval])) by (instance)",
       "legendFormat": "{{instance}}_Writes completed"
      }
     ]
    },
    {
     "title": "Node Disk Average Queue Size",
     "type": "timeseries",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Components Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Used Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", name=\"deploy_hserver\"}[$interval])) BY (instance, name) * 100)",
       "legendFormat": "{{instance}}-server"
      },
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", name=\"deploy_hstore\"}[$interval])) BY (instance, name) * 100)",
       "legendFormat": "{{instance}}-store"
      },
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", name=\"deploy_meta\"}[$interval])) BY (instance, name) * 100)",
       "legendFormat": "{{instance}}-meta"
      },
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\", cluster_id=~\"$clusterId\", name=~\"IOTASK.*\"}[$interval])) BY (instance, name) * 100)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Container Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\", name=\"deploy_hserver\"}) BY (instance, name))",
       "legendFormat": "{{instance}}-server"
      },
      {
       "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\", name=\"deploy_hstore\"}) BY (instance, name))",
       "legendFormat": "{{instance}}-store"
      },
      {
       "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\", name=\"deploy_meta\"}) BY (instance, name))",
       "legendFormat": "{{instance}}-meta"
      },
      {
       "expr": "(sum(container_memory_working_set_bytes{instance=~\"$host\", cluster_id=~\"$clusterId\", name=~\"IOTASK.*\"}) BY (instance, name))",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    }
   ]
  }
 ]
}